### PR TITLE
Homepage, Modal and Context

### PR DESCRIPTION
**Pull request by Tanay-J**
This PR includes
- Homepage (includes Navbar, Welcome message, Add task button, List of tasks)
- Modal to take inputs from user and create/edit tasks
- Context to manage tasks seamlessly

**Preview**
https://pomodoro-app-git-homepage-tanay-j.vercel.app/

### CODE REVIEW

**Review by ajit-sharmaGH — APPROVED** [review]
Looks good
You can merge it

**Review by nikhilmalviya-dev — APPROVED** [review]
good structured

**Review by omjadhav85 — APPROVED** [review]
Loved the UI!! Really nice coding. Liked how you have broke down everything into smaller components. Cool usage of reducer...really made tasks easy to handle. Great work! Good to merge!

**Review by shuklahimanshu81 — APPROVED** [review]
Your code structure is clean. Naming convention is impressive will try to implement them while building my  project. One thing that I like most is UI . Minimal but looks really clean.

**Pull request merged**
